# Site settings
title: Entropic Blog
name: Entropic Blog by Jakub Dundalek
description: "Fixing Entropy through software"
url: "https://dundalek.com"
author:
  name: "Jakub Dundalek"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /entropic/:title
paginate: 5
paginate_path: /entropic/page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
